/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
* Controls which pipelines display this field. Default is show_in_all=true. Note that fields marked as important or required must be visible in the pipelines where they are configured.
* @export
* @interface AddDealFieldRequestUiVisibilityShowInPipelines
*/
export interface AddDealFieldRequestUiVisibilityShowInPipelines {
    /**
    * When true, the field is visible in all pipelines. When false, visibility is controlled by pipeline_ids. Default is true.
    * @type {boolean}
    */
    'show_in_all'?: boolean;
    /**
    * Array of pipeline IDs where the field should be visible. Only used when show_in_all is false. Must reference valid, active pipelines.
    * @type {Array<number>}
    */
    'pipeline_ids'?: Array<number>;
}

