/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AddActivityRequestAttendeesInner } from './add-activity-request-attendees-inner';
// May contain unused imports in some cases
// @ts-ignore
import { AddActivityRequestLocation } from './add-activity-request-location';
// May contain unused imports in some cases
// @ts-ignore
import { AddActivityRequestParticipantsInner } from './add-activity-request-participants-inner';

/**
* 
* @export
* @interface AddActivityRequest
*/
export interface AddActivityRequest {
    /**
    * The subject of the activity
    * @type {string}
    */
    'subject'?: string;
    /**
    * The type of the activity
    * @type {string}
    */
    'type'?: string;
    /**
    * The ID of the user who owns the activity
    * @type {number}
    */
    'owner_id'?: number;
    /**
    * The ID of the deal linked to the activity
    * @type {number}
    */
    'deal_id'?: number;
    /**
    * The ID of the lead linked to the activity
    * @type {string}
    */
    'lead_id'?: string;
    /**
    * The ID of the person linked to the activity
    * @type {number}
    */
    'person_id'?: number;
    /**
    * The ID of the organization linked to the activity
    * @type {number}
    */
    'org_id'?: number;
    /**
    * The ID of the project linked to the activity
    * @type {number}
    */
    'project_id'?: number;
    /**
    * The due date of the activity
    * @type {string}
    */
    'due_date'?: string;
    /**
    * The due time of the activity
    * @type {string}
    */
    'due_time'?: string;
    /**
    * The duration of the activity
    * @type {string}
    */
    'duration'?: string;
    /**
    * Whether the activity marks the assignee as busy or not in their calendar
    * @type {boolean}
    */
    'busy'?: boolean;
    /**
    * Whether the activity is marked as done or not
    * @type {boolean}
    */
    'done'?: boolean;
    /**
    * 
    * @type {AddActivityRequestLocation}
    */
    'location'?: AddActivityRequestLocation;
    /**
    * The participants of the activity
    * @type {Array<AddActivityRequestParticipantsInner>}
    */
    'participants'?: Array<AddActivityRequestParticipantsInner>;
    /**
    * The attendees of the activity
    * @type {Array<AddActivityRequestAttendeesInner>}
    */
    'attendees'?: Array<AddActivityRequestAttendeesInner>;
    /**
    * The public description of the activity
    * @type {string}
    */
    'public_description'?: string;
    /**
    * The priority of the activity. Mappable to a specific string using activityFields API.
    * @type {number}
    */
    'priority'?: number;
    /**
    * The note of the activity
    * @type {string}
    */
    'note'?: string;
}

