/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ItemSearchItem } from './item-search-item';

/**
* 
* @export
* @interface GetItemSearchResponseDataData
*/
export interface GetItemSearchResponseDataData {
    /**
    * The array of found items
    * @type {Array<ItemSearchItem>}
    */
    'items'?: Array<ItemSearchItem>;
    /**
    * The array of related items if `search_for_related_items` was enabled
    * @type {Array<ItemSearchItem>}
    */
    'related_items'?: Array<ItemSearchItem>;
}

