/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FollowerChangelogItem } from './follower-changelog-item';
// May contain unused imports in some cases
// @ts-ignore
import { GetActivitiesResponseAllOfAdditionalData } from './get-activities-response-all-of-additional-data';

/**
* 
* @export
* @interface GetFollowerChangelogsResponseAllOf
*/
export interface GetFollowerChangelogsResponseAllOf {
    /**
    * Follower changelogs array
    * @type {Array<FollowerChangelogItem>}
    */
    'data'?: Array<FollowerChangelogItem>;
    /**
    * 
    * @type {GetActivitiesResponseAllOfAdditionalData}
    */
    'additional_data'?: GetActivitiesResponseAllOfAdditionalData;
}

