/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
* 
* @export
* @interface UpdateProjectPhaseRequest
*/
export interface UpdateProjectPhaseRequest {
    /**
    * The name of the project phase
    * @type {string}
    */
    'name'?: string;
    /**
    * The ID of the project board to add the phase to
    * @type {number}
    */
    'board_id'?: number;
    /**
    * The order of the phase within its board. Must be between 1 and the total number of phases on the board + 1.
    * @type {number}
    */
    'order_nr'?: number;
}

