/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AddPersonPictureResponseAllOf from './AddPersonPictureResponseAllOf';
import BaseResponse from './BaseResponse';
import RelatedPictureData from './RelatedPictureData';

/**
 * The AddPersonPictureResponse model module.
 * @module model/AddPersonPictureResponse
 * @version 1.0.0
 */
class AddPersonPictureResponse {
    /**
     * Constructs a new <code>AddPersonPictureResponse</code>.
     * @alias module:model/AddPersonPictureResponse
     * @implements module:model/BaseResponse
     * @implements module:model/AddPersonPictureResponseAllOf
     */
    constructor() { 
        BaseResponse.initialize(this);AddPersonPictureResponseAllOf.initialize(this);
        AddPersonPictureResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AddPersonPictureResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddPersonPictureResponse} obj Optional instance to populate.
     * @return {module:model/AddPersonPictureResponse} The populated <code>AddPersonPictureResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddPersonPictureResponse();
            BaseResponse.constructFromObject(data, obj);
            AddPersonPictureResponseAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');

                delete data['success'];
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = RelatedPictureData.constructFromObject(data['data']);

                delete data['data'];
            }

            if (Object.keys(data).length > 0) {
                Object.assign(obj, data);
            }

        }
        return obj;
    }


}

/**
 * If the response is successful or not
 * @member {Boolean} success
 */
AddPersonPictureResponse.prototype['success'] = undefined;

/**
 * @member {module:model/RelatedPictureData} data
 */
AddPersonPictureResponse.prototype['data'] = undefined;


// Implement BaseResponse interface:
/**
 * If the response is successful or not
 * @member {Boolean} success
 */
BaseResponse.prototype['success'] = undefined;
// Implement AddPersonPictureResponseAllOf interface:
/**
 * @member {module:model/RelatedPictureData} data
 */
AddPersonPictureResponseAllOf.prototype['data'] = undefined;




export default AddPersonPictureResponse;

