/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AddTeamUserRequest model module.
 * @module model/AddTeamUserRequest
 * @version 1.0.0
 */
class AddTeamUserRequest {
    /**
     * Constructs a new <code>AddTeamUserRequest</code>.
     * @alias module:model/AddTeamUserRequest
     * @param users {Array.<Number>} The list of user IDs
     */
    constructor(users) { 
        
        AddTeamUserRequest.initialize(this, users);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, users) { 
        obj['users'] = users;
    }

    /**
     * Constructs a <code>AddTeamUserRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddTeamUserRequest} obj Optional instance to populate.
     * @return {module:model/AddTeamUserRequest} The populated <code>AddTeamUserRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddTeamUserRequest();

            if (data.hasOwnProperty('users')) {
                obj['users'] = ApiClient.convertToType(data['users'], ['Number']);

                delete data['users'];
            }

            if (Object.keys(data).length > 0) {
                Object.assign(obj, data);
            }

        }
        return obj;
    }


}

/**
 * The list of user IDs
 * @member {Array.<Number>} users
 */
AddTeamUserRequest.prototype['users'] = undefined;






export default AddTeamUserRequest;

