/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MailThreadParticipant from './MailThreadParticipant';

/**
 * The BaseMailThreadAllOfParties model module.
 * @module model/BaseMailThreadAllOfParties
 * @version 1.0.0
 */
class BaseMailThreadAllOfParties {
    /**
     * Constructs a new <code>BaseMailThreadAllOfParties</code>.
     * Parties of the mail thread
     * @alias module:model/BaseMailThreadAllOfParties
     */
    constructor() { 
        
        BaseMailThreadAllOfParties.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BaseMailThreadAllOfParties</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BaseMailThreadAllOfParties} obj Optional instance to populate.
     * @return {module:model/BaseMailThreadAllOfParties} The populated <code>BaseMailThreadAllOfParties</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BaseMailThreadAllOfParties();

            if (data.hasOwnProperty('to')) {
                obj['to'] = ApiClient.convertToType(data['to'], [MailThreadParticipant]);

                delete data['to'];
            }
            if (data.hasOwnProperty('from')) {
                obj['from'] = ApiClient.convertToType(data['from'], [MailThreadParticipant]);

                delete data['from'];
            }

            if (Object.keys(data).length > 0) {
                Object.assign(obj, data);
            }

        }
        return obj;
    }


}

/**
 * Recipients of the mail thread
 * @member {Array.<module:model/MailThreadParticipant>} to
 */
BaseMailThreadAllOfParties.prototype['to'] = undefined;

/**
 * Senders of the mail thread
 * @member {Array.<module:model/MailThreadParticipant>} from
 */
BaseMailThreadAllOfParties.prototype['from'] = undefined;






export default BaseMailThreadAllOfParties;

