/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeleteUsersFromATeam model module.
 * @module model/DeleteUsersFromATeam
 * @version 1.0.0
 */
class DeleteUsersFromATeam {
    /**
     * Constructs a new <code>DeleteUsersFromATeam</code>.
     * @alias module:model/DeleteUsersFromATeam
     * @param users {Array.<Number>} List of User IDs
     */
    constructor(users) { 
        
        DeleteUsersFromATeam.initialize(this, users);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, users) { 
        obj['users'] = users;
    }

    /**
     * Constructs a <code>DeleteUsersFromATeam</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeleteUsersFromATeam} obj Optional instance to populate.
     * @return {module:model/DeleteUsersFromATeam} The populated <code>DeleteUsersFromATeam</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeleteUsersFromATeam();

            if (data.hasOwnProperty('users')) {
                obj['users'] = ApiClient.convertToType(data['users'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * List of User IDs
 * @member {Array.<Number>} users
 */
DeleteUsersFromATeam.prototype['users'] = undefined;






export default DeleteUsersFromATeam;

