/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FiltersPostResponseAllOfData from './FiltersPostResponseAllOfData';

/**
 * The FiltersPostResponseAllOf model module.
 * @module model/FiltersPostResponseAllOf
 * @version 1.0.0
 */
class FiltersPostResponseAllOf {
    /**
     * Constructs a new <code>FiltersPostResponseAllOf</code>.
     * @alias module:model/FiltersPostResponseAllOf
     */
    constructor() { 
        
        FiltersPostResponseAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FiltersPostResponseAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FiltersPostResponseAllOf} obj Optional instance to populate.
     * @return {module:model/FiltersPostResponseAllOf} The populated <code>FiltersPostResponseAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FiltersPostResponseAllOf();

            if (data.hasOwnProperty('data')) {
                obj['data'] = FiltersPostResponseAllOfData.constructFromObject(data['data']);

                delete data['data'];
            }

            if (Object.keys(data).length > 0) {
                Object.assign(obj, data);
            }

        }
        return obj;
    }


}

/**
 * @member {module:model/FiltersPostResponseAllOfData} data
 */
FiltersPostResponseAllOf.prototype['data'] = undefined;






export default FiltersPostResponseAllOf;

