/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BaseResponse from './BaseResponse';
import FilterGetItem from './FilterGetItem';
import FiltersBulkGetResponseAllOf from './FiltersBulkGetResponseAllOf';

/**
 * The FiltersBulkGetResponse model module.
 * @module model/FiltersBulkGetResponse
 * @version 1.0.0
 */
class FiltersBulkGetResponse {
    /**
     * Constructs a new <code>FiltersBulkGetResponse</code>.
     * @alias module:model/FiltersBulkGetResponse
     * @implements module:model/BaseResponse
     * @implements module:model/FiltersBulkGetResponseAllOf
     */
    constructor() { 
        BaseResponse.initialize(this);FiltersBulkGetResponseAllOf.initialize(this);
        FiltersBulkGetResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FiltersBulkGetResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FiltersBulkGetResponse} obj Optional instance to populate.
     * @return {module:model/FiltersBulkGetResponse} The populated <code>FiltersBulkGetResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FiltersBulkGetResponse();
            BaseResponse.constructFromObject(data, obj);
            FiltersBulkGetResponseAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');

                delete data['success'];
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [FilterGetItem]);

                delete data['data'];
            }

            if (Object.keys(data).length > 0) {
                Object.assign(obj, data);
            }

        }
        return obj;
    }


}

/**
 * If the response is successful or not
 * @member {Boolean} success
 */
FiltersBulkGetResponse.prototype['success'] = undefined;

/**
 * The array of filters
 * @member {Array.<module:model/FilterGetItem>} data
 */
FiltersBulkGetResponse.prototype['data'] = undefined;


// Implement BaseResponse interface:
/**
 * If the response is successful or not
 * @member {Boolean} success
 */
BaseResponse.prototype['success'] = undefined;
// Implement FiltersBulkGetResponseAllOf interface:
/**
 * The array of filters
 * @member {Array.<module:model/FilterGetItem>} data
 */
FiltersBulkGetResponseAllOf.prototype['data'] = undefined;




export default FiltersBulkGetResponse;

