/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BaseResponse from './BaseResponse';
import GetDealsConversionRatesInPipelineAllOf from './GetDealsConversionRatesInPipelineAllOf';
import GetDealsConversionRatesInPipelineAllOfData from './GetDealsConversionRatesInPipelineAllOfData';

/**
 * The GetDealsConversionRatesInPipeline model module.
 * @module model/GetDealsConversionRatesInPipeline
 * @version 1.0.0
 */
class GetDealsConversionRatesInPipeline {
    /**
     * Constructs a new <code>GetDealsConversionRatesInPipeline</code>.
     * @alias module:model/GetDealsConversionRatesInPipeline
     * @implements module:model/BaseResponse
     * @implements module:model/GetDealsConversionRatesInPipelineAllOf
     */
    constructor() { 
        BaseResponse.initialize(this);GetDealsConversionRatesInPipelineAllOf.initialize(this);
        GetDealsConversionRatesInPipeline.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetDealsConversionRatesInPipeline</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetDealsConversionRatesInPipeline} obj Optional instance to populate.
     * @return {module:model/GetDealsConversionRatesInPipeline} The populated <code>GetDealsConversionRatesInPipeline</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetDealsConversionRatesInPipeline();
            BaseResponse.constructFromObject(data, obj);
            GetDealsConversionRatesInPipelineAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');

                delete data['success'];
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = GetDealsConversionRatesInPipelineAllOfData.constructFromObject(data['data']);

                delete data['data'];
            }

            if (Object.keys(data).length > 0) {
                Object.assign(obj, data);
            }

        }
        return obj;
    }


}

/**
 * If the response is successful or not
 * @member {Boolean} success
 */
GetDealsConversionRatesInPipeline.prototype['success'] = undefined;

/**
 * @member {module:model/GetDealsConversionRatesInPipelineAllOfData} data
 */
GetDealsConversionRatesInPipeline.prototype['data'] = undefined;


// Implement BaseResponse interface:
/**
 * If the response is successful or not
 * @member {Boolean} success
 */
BaseResponse.prototype['success'] = undefined;
// Implement GetDealsConversionRatesInPipelineAllOf interface:
/**
 * @member {module:model/GetDealsConversionRatesInPipelineAllOfData} data
 */
GetDealsConversionRatesInPipelineAllOf.prototype['data'] = undefined;




export default GetDealsConversionRatesInPipeline;

