/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetDealsMovementsInPipelineAllOfDataNewDealsFormattedValues from './GetDealsMovementsInPipelineAllOfDataNewDealsFormattedValues';
import GetDealsMovementsInPipelineAllOfDataNewDealsValues from './GetDealsMovementsInPipelineAllOfDataNewDealsValues';

/**
 * The GetDealsMovementsInPipelineAllOfDataNewDeals model module.
 * @module model/GetDealsMovementsInPipelineAllOfDataNewDeals
 * @version 1.0.0
 */
class GetDealsMovementsInPipelineAllOfDataNewDeals {
    /**
     * Constructs a new <code>GetDealsMovementsInPipelineAllOfDataNewDeals</code>.
     * Deals summary
     * @alias module:model/GetDealsMovementsInPipelineAllOfDataNewDeals
     */
    constructor() { 
        
        GetDealsMovementsInPipelineAllOfDataNewDeals.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetDealsMovementsInPipelineAllOfDataNewDeals</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetDealsMovementsInPipelineAllOfDataNewDeals} obj Optional instance to populate.
     * @return {module:model/GetDealsMovementsInPipelineAllOfDataNewDeals} The populated <code>GetDealsMovementsInPipelineAllOfDataNewDeals</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetDealsMovementsInPipelineAllOfDataNewDeals();

            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('deals_ids')) {
                obj['deals_ids'] = ApiClient.convertToType(data['deals_ids'], ['Number']);
            }
            if (data.hasOwnProperty('values')) {
                obj['values'] = GetDealsMovementsInPipelineAllOfDataNewDealsValues.constructFromObject(data['values']);
            }
            if (data.hasOwnProperty('formatted_values')) {
                obj['formatted_values'] = GetDealsMovementsInPipelineAllOfDataNewDealsFormattedValues.constructFromObject(data['formatted_values']);
            }
        }
        return obj;
    }


}

/**
 * Deals count
 * @member {Number} count
 */
GetDealsMovementsInPipelineAllOfDataNewDeals.prototype['count'] = undefined;

/**
 * IDs of the Deals that have been moved
 * @member {Array.<Number>} deals_ids
 */
GetDealsMovementsInPipelineAllOfDataNewDeals.prototype['deals_ids'] = undefined;

/**
 * @member {module:model/GetDealsMovementsInPipelineAllOfDataNewDealsValues} values
 */
GetDealsMovementsInPipelineAllOfDataNewDeals.prototype['values'] = undefined;

/**
 * @member {module:model/GetDealsMovementsInPipelineAllOfDataNewDealsFormattedValues} formatted_values
 */
GetDealsMovementsInPipelineAllOfDataNewDeals.prototype['formatted_values'] = undefined;






export default GetDealsMovementsInPipelineAllOfDataNewDeals;

