/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RecentDataProduct from './RecentDataProduct';

/**
 * The GetRecentsDataProduct model module.
 * @module model/GetRecentsDataProduct
 * @version 1.0.0
 */
class GetRecentsDataProduct {
    /**
     * Constructs a new <code>GetRecentsDataProduct</code>.
     * @alias module:model/GetRecentsDataProduct
     */
    constructor() { 
        
        GetRecentsDataProduct.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetRecentsDataProduct</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetRecentsDataProduct} obj Optional instance to populate.
     * @return {module:model/GetRecentsDataProduct} The populated <code>GetRecentsDataProduct</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetRecentsDataProduct();

            if (data.hasOwnProperty('item')) {
                obj['item'] = ApiClient.convertToType(data['item'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = RecentDataProduct.constructFromObject(data['data']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/GetRecentsDataProduct.ItemEnum} item
 */
GetRecentsDataProduct.prototype['item'] = undefined;

/**
 * @member {Number} id
 */
GetRecentsDataProduct.prototype['id'] = undefined;

/**
 * @member {module:model/RecentDataProduct} data
 */
GetRecentsDataProduct.prototype['data'] = undefined;





/**
 * Allowed values for the <code>item</code> property.
 * @enum {String}
 * @readonly
 */
GetRecentsDataProduct['ItemEnum'] = {

    /**
     * value: "product"
     * @const
     */
    "product": "product"
};



export default GetRecentsDataProduct;

