/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Assignee from './Assignee';
import Duration from './Duration';
import ExpectedOutcome from './ExpectedOutcome';
import GoalType from './GoalType';

/**
 * The GoalsResponseComponentAllOf model module.
 * @module model/GoalsResponseComponentAllOf
 * @version 1.0.0
 */
class GoalsResponseComponentAllOf {
    /**
     * Constructs a new <code>GoalsResponseComponentAllOf</code>.
     * @alias module:model/GoalsResponseComponentAllOf
     */
    constructor() { 
        
        GoalsResponseComponentAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GoalsResponseComponentAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GoalsResponseComponentAllOf} obj Optional instance to populate.
     * @return {module:model/GoalsResponseComponentAllOf} The populated <code>GoalsResponseComponentAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GoalsResponseComponentAllOf();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('owner_id')) {
                obj['owner_id'] = ApiClient.convertToType(data['owner_id'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], GoalType);
            }
            if (data.hasOwnProperty('assignee')) {
                obj['assignee'] = ApiClient.convertToType(data['assignee'], Assignee);
            }
            if (data.hasOwnProperty('interval')) {
                obj['interval'] = ApiClient.convertToType(data['interval'], 'String');
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], Duration);
            }
            if (data.hasOwnProperty('expected_outcome')) {
                obj['expected_outcome'] = ApiClient.convertToType(data['expected_outcome'], ExpectedOutcome);
            }
            if (data.hasOwnProperty('is_active')) {
                obj['is_active'] = ApiClient.convertToType(data['is_active'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * ID of the goal
 * @member {String} id
 */
GoalsResponseComponentAllOf.prototype['id'] = undefined;

/**
 * ID of the creator of the goal
 * @member {String} owner_id
 */
GoalsResponseComponentAllOf.prototype['owner_id'] = undefined;

/**
 * The title of the goal
 * @member {String} title
 */
GoalsResponseComponentAllOf.prototype['title'] = undefined;

/**
 * @member {module:model/GoalType} type
 */
GoalsResponseComponentAllOf.prototype['type'] = undefined;

/**
 * @member {module:model/Assignee} assignee
 */
GoalsResponseComponentAllOf.prototype['assignee'] = undefined;

/**
 * Interval of the goal
 * @member {String} interval
 */
GoalsResponseComponentAllOf.prototype['interval'] = undefined;

/**
 * @member {module:model/Duration} duration
 */
GoalsResponseComponentAllOf.prototype['duration'] = undefined;

/**
 * @member {module:model/ExpectedOutcome} expected_outcome
 */
GoalsResponseComponentAllOf.prototype['expected_outcome'] = undefined;

/**
 * If the goal is currently active or not
 * @member {Boolean} is_active
 */
GoalsResponseComponentAllOf.prototype['is_active'] = undefined;






export default GoalsResponseComponentAllOf;

