/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2009Data model module.
 * @module model/InlineResponse2009Data
 * @version 1.0.0
 */
class InlineResponse2009Data {
    /**
     * Constructs a new <code>InlineResponse2009Data</code>.
     * The array of Deals filtered by name
     * @alias module:model/InlineResponse2009Data
     */
    constructor() { 
        
        InlineResponse2009Data.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse2009Data</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2009Data} obj Optional instance to populate.
     * @return {module:model/InlineResponse2009Data} The populated <code>InlineResponse2009Data</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2009Data();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
            }
            if (data.hasOwnProperty('visible_to')) {
                obj['visible_to'] = ApiClient.convertToType(data['visible_to'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('person_name')) {
                obj['person_name'] = ApiClient.convertToType(data['person_name'], 'String');
            }
            if (data.hasOwnProperty('person_id')) {
                obj['person_id'] = ApiClient.convertToType(data['person_id'], 'Number');
            }
            if (data.hasOwnProperty('organization_name')) {
                obj['organization_name'] = ApiClient.convertToType(data['organization_name'], 'String');
            }
            if (data.hasOwnProperty('organization_id')) {
                obj['organization_id'] = ApiClient.convertToType(data['organization_id'], 'Number');
            }
            if (data.hasOwnProperty('formatted_value')) {
                obj['formatted_value'] = ApiClient.convertToType(data['formatted_value'], 'String');
            }
            if (data.hasOwnProperty('cc_email')) {
                obj['cc_email'] = ApiClient.convertToType(data['cc_email'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The ID of the Deal
 * @member {Number} id
 */
InlineResponse2009Data.prototype['id'] = undefined;

/**
 * The title of the Deal
 * @member {String} title
 */
InlineResponse2009Data.prototype['title'] = undefined;

/**
 * The ID of the User who is associated with the Deal
 * @member {Number} user_id
 */
InlineResponse2009Data.prototype['user_id'] = undefined;

/**
 * The visibility of the Deal
 * @member {String} visible_to
 */
InlineResponse2009Data.prototype['visible_to'] = undefined;

/**
 * The status of the Deal
 * @member {String} status
 */
InlineResponse2009Data.prototype['status'] = undefined;

/**
 * The value of the Deal
 * @member {Number} value
 */
InlineResponse2009Data.prototype['value'] = undefined;

/**
 * The currency associated with the Deal
 * @member {String} currency
 */
InlineResponse2009Data.prototype['currency'] = undefined;

/**
 * The name of the Person associated with the Deal
 * @member {String} person_name
 */
InlineResponse2009Data.prototype['person_name'] = undefined;

/**
 * The ID of the Person associated with the Deal
 * @member {Number} person_id
 */
InlineResponse2009Data.prototype['person_id'] = undefined;

/**
 * The name of the Organization associated with the Deal
 * @member {String} organization_name
 */
InlineResponse2009Data.prototype['organization_name'] = undefined;

/**
 * The ID of the Person associated with the Deal
 * @member {Number} organization_id
 */
InlineResponse2009Data.prototype['organization_id'] = undefined;

/**
 * The Deal value formatted with selected currency. E.g. US$500
 * @member {String} formatted_value
 */
InlineResponse2009Data.prototype['formatted_value'] = undefined;

/**
 * The Cc email of the Deal
 * @member {String} cc_email
 */
InlineResponse2009Data.prototype['cc_email'] = undefined;






export default InlineResponse2009Data;

