/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ItemSearchAdditionalData from './ItemSearchAdditionalData';
import LeadSearchResponseAllOfData from './LeadSearchResponseAllOfData';

/**
 * The LeadSearchResponseAllOf model module.
 * @module model/LeadSearchResponseAllOf
 * @version 1.0.0
 */
class LeadSearchResponseAllOf {
    /**
     * Constructs a new <code>LeadSearchResponseAllOf</code>.
     * @alias module:model/LeadSearchResponseAllOf
     */
    constructor() { 
        
        LeadSearchResponseAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LeadSearchResponseAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LeadSearchResponseAllOf} obj Optional instance to populate.
     * @return {module:model/LeadSearchResponseAllOf} The populated <code>LeadSearchResponseAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LeadSearchResponseAllOf();

            if (data.hasOwnProperty('data')) {
                obj['data'] = LeadSearchResponseAllOfData.constructFromObject(data['data']);

                delete data['data'];
            }
            if (data.hasOwnProperty('additional_data')) {
                obj['additional_data'] = ItemSearchAdditionalData.constructFromObject(data['additional_data']);

                delete data['additional_data'];
            }

            if (Object.keys(data).length > 0) {
                Object.assign(obj, data);
            }

        }
        return obj;
    }


}

/**
 * @member {module:model/LeadSearchResponseAllOfData} data
 */
LeadSearchResponseAllOf.prototype['data'] = undefined;

/**
 * @member {module:model/ItemSearchAdditionalData} additional_data
 */
LeadSearchResponseAllOf.prototype['additional_data'] = undefined;






export default LeadSearchResponseAllOf;

