/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LeadResponse from './LeadResponse';

/**
 * The OneLeadResponse200 model module.
 * @module model/OneLeadResponse200
 * @version 1.0.0
 */
class OneLeadResponse200 {
    /**
     * Constructs a new <code>OneLeadResponse200</code>.
     * @alias module:model/OneLeadResponse200
     */
    constructor() { 
        
        OneLeadResponse200.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OneLeadResponse200</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OneLeadResponse200} obj Optional instance to populate.
     * @return {module:model/OneLeadResponse200} The populated <code>OneLeadResponse200</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OneLeadResponse200();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');

                delete data['success'];
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = LeadResponse.constructFromObject(data['data']);

                delete data['data'];
            }

            if (Object.keys(data).length > 0) {
                Object.assign(obj, data);
            }

        }
        return obj;
    }


}

/**
 * @member {Boolean} success
 */
OneLeadResponse200.prototype['success'] = undefined;

/**
 * @member {module:model/LeadResponse} data
 */
OneLeadResponse200.prototype['data'] = undefined;






export default OneLeadResponse200;

