/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DealSearchItemItemOwner from './DealSearchItemItemOwner';

/**
 * The OrganizationSearchItemItem model module.
 * @module model/OrganizationSearchItemItem
 * @version 1.0.0
 */
class OrganizationSearchItemItem {
    /**
     * Constructs a new <code>OrganizationSearchItemItem</code>.
     * @alias module:model/OrganizationSearchItemItem
     */
    constructor() { 
        
        OrganizationSearchItemItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OrganizationSearchItemItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrganizationSearchItemItem} obj Optional instance to populate.
     * @return {module:model/OrganizationSearchItemItem} The populated <code>OrganizationSearchItemItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrganizationSearchItemItem();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');

                delete data['id'];
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');

                delete data['type'];
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');

                delete data['name'];
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');

                delete data['address'];
            }
            if (data.hasOwnProperty('visible_to')) {
                obj['visible_to'] = ApiClient.convertToType(data['visible_to'], 'Number');

                delete data['visible_to'];
            }
            if (data.hasOwnProperty('owner')) {
                obj['owner'] = DealSearchItemItemOwner.constructFromObject(data['owner']);

                delete data['owner'];
            }
            if (data.hasOwnProperty('custom_fields')) {
                obj['custom_fields'] = ApiClient.convertToType(data['custom_fields'], ['String']);

                delete data['custom_fields'];
            }
            if (data.hasOwnProperty('notes')) {
                obj['notes'] = ApiClient.convertToType(data['notes'], ['String']);

                delete data['notes'];
            }

            if (Object.keys(data).length > 0) {
                Object.assign(obj, data);
            }

        }
        return obj;
    }


}

/**
 * The ID of the organization
 * @member {Number} id
 */
OrganizationSearchItemItem.prototype['id'] = undefined;

/**
 * The type of the item
 * @member {String} type
 */
OrganizationSearchItemItem.prototype['type'] = undefined;

/**
 * The name of the organization
 * @member {String} name
 */
OrganizationSearchItemItem.prototype['name'] = undefined;

/**
 * The address of the organization
 * @member {String} address
 */
OrganizationSearchItemItem.prototype['address'] = undefined;

/**
 * The visibility of the organization
 * @member {Number} visible_to
 */
OrganizationSearchItemItem.prototype['visible_to'] = undefined;

/**
 * @member {module:model/DealSearchItemItemOwner} owner
 */
OrganizationSearchItemItem.prototype['owner'] = undefined;

/**
 * Custom fields
 * @member {Array.<String>} custom_fields
 */
OrganizationSearchItemItem.prototype['custom_fields'] = undefined;

/**
 * An array of notes
 * @member {Array.<String>} notes
 */
OrganizationSearchItemItem.prototype['notes'] = undefined;






export default OrganizationSearchItemItem;

