/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OrganizationItemAllOf model module.
 * @module model/OrganizationItemAllOf
 * @version 1.0.0
 */
class OrganizationItemAllOf {
    /**
     * Constructs a new <code>OrganizationItemAllOf</code>.
     * @alias module:model/OrganizationItemAllOf
     */
    constructor() { 
        
        OrganizationItemAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OrganizationItemAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrganizationItemAllOf} obj Optional instance to populate.
     * @return {module:model/OrganizationItemAllOf} The populated <code>OrganizationItemAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrganizationItemAllOf();

            if (data.hasOwnProperty('last_activity')) {
                obj['last_activity'] = ApiClient.convertToType(data['last_activity'], Object);

                delete data['last_activity'];
            }
            if (data.hasOwnProperty('next_activity')) {
                obj['next_activity'] = ApiClient.convertToType(data['next_activity'], Object);

                delete data['next_activity'];
            }

            if (Object.keys(data).length > 0) {
                Object.assign(obj, data);
            }

        }
        return obj;
    }


}

/**
 * Please refer to response schema of <a href=\"https://developers.pipedrive.com/docs/api/v1/Activities#getActivity\">Activity</a>
 * @member {Object} last_activity
 */
OrganizationItemAllOf.prototype['last_activity'] = undefined;

/**
 * Please refer to response schema of <a href=\"https://developers.pipedrive.com/docs/api/v1/Activities#getActivity\">Activity</a>
 * @member {Object} next_activity
 */
OrganizationItemAllOf.prototype['next_activity'] = undefined;






export default OrganizationItemAllOf;

