/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GoalsResponseComponent from './GoalsResponseComponent';

/**
 * The PostGoalResponse model module.
 * @module model/PostGoalResponse
 * @version 1.0.0
 */
class PostGoalResponse {
    /**
     * Constructs a new <code>PostGoalResponse</code>.
     * @alias module:model/PostGoalResponse
     */
    constructor() { 
        
        PostGoalResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostGoalResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostGoalResponse} obj Optional instance to populate.
     * @return {module:model/PostGoalResponse} The populated <code>PostGoalResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostGoalResponse();

            if (data.hasOwnProperty('goal')) {
                obj['goal'] = GoalsResponseComponent.constructFromObject(data['goal']);

                delete data['goal'];
            }

            if (Object.keys(data).length > 0) {
                Object.assign(obj, data);
            }

        }
        return obj;
    }


}

/**
 * @member {module:model/GoalsResponseComponent} goal
 */
PostGoalResponse.prototype['goal'] = undefined;






export default PostGoalResponse;

