/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RequiredPostProjectParameters model module.
 * @module model/RequiredPostProjectParameters
 * @version 1.0.0
 */
class RequiredPostProjectParameters {
    /**
     * Constructs a new <code>RequiredPostProjectParameters</code>.
     * @alias module:model/RequiredPostProjectParameters
     * @param title {String} The title of the project
     * @param boardId {Number} The ID of a project board
     * @param phaseId {Number} The ID of a phase on a project board
     */
    constructor(title, boardId, phaseId) { 
        
        RequiredPostProjectParameters.initialize(this, title, boardId, phaseId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, title, boardId, phaseId) { 
        obj['title'] = title;
        obj['board_id'] = boardId;
        obj['phase_id'] = phaseId;
    }

    /**
     * Constructs a <code>RequiredPostProjectParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RequiredPostProjectParameters} obj Optional instance to populate.
     * @return {module:model/RequiredPostProjectParameters} The populated <code>RequiredPostProjectParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RequiredPostProjectParameters();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');

                delete data['title'];
            }
            if (data.hasOwnProperty('board_id')) {
                obj['board_id'] = ApiClient.convertToType(data['board_id'], 'Number');

                delete data['board_id'];
            }
            if (data.hasOwnProperty('phase_id')) {
                obj['phase_id'] = ApiClient.convertToType(data['phase_id'], 'Number');

                delete data['phase_id'];
            }

            if (Object.keys(data).length > 0) {
                Object.assign(obj, data);
            }

        }
        return obj;
    }


}

/**
 * The title of the project
 * @member {String} title
 */
RequiredPostProjectParameters.prototype['title'] = undefined;

/**
 * The ID of a project board
 * @member {Number} board_id
 */
RequiredPostProjectParameters.prototype['board_id'] = undefined;

/**
 * The ID of a phase on a project board
 * @member {Number} phase_id
 */
RequiredPostProjectParameters.prototype['phase_id'] = undefined;






export default RequiredPostProjectParameters;

