/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BaseResponse from './BaseResponse';
import BaseUserMe from './BaseUserMe';
import UserMeAllOf from './UserMeAllOf';

/**
 * The UserMe model module.
 * @module model/UserMe
 * @version 1.0.0
 */
class UserMe {
    /**
     * Constructs a new <code>UserMe</code>.
     * @alias module:model/UserMe
     * @implements module:model/BaseResponse
     * @implements module:model/UserMeAllOf
     */
    constructor() { 
        BaseResponse.initialize(this);UserMeAllOf.initialize(this);
        UserMe.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserMe</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserMe} obj Optional instance to populate.
     * @return {module:model/UserMe} The populated <code>UserMe</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserMe();
            BaseResponse.constructFromObject(data, obj);
            UserMeAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');

                delete data['success'];
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = BaseUserMe.constructFromObject(data['data']);

                delete data['data'];
            }

            if (Object.keys(data).length > 0) {
                Object.assign(obj, data);
            }

        }
        return obj;
    }


}

/**
 * If the response is successful or not
 * @member {Boolean} success
 */
UserMe.prototype['success'] = undefined;

/**
 * @member {module:model/BaseUserMe} data
 */
UserMe.prototype['data'] = undefined;


// Implement BaseResponse interface:
/**
 * If the response is successful or not
 * @member {Boolean} success
 */
BaseResponse.prototype['success'] = undefined;
// Implement UserMeAllOf interface:
/**
 * @member {module:model/BaseUserMe} data
 */
UserMeAllOf.prototype['data'] = undefined;




export default UserMe;

