/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
* 
* @export
* @interface GetFieldAllOf
*/
export interface GetFieldAllOf {
    /**
    * List of all possible field types
    * @type {string}
    */
    'field_type'?: GetFieldAllOfFieldTypeConst;
}

                export const GetFieldAllOfFieldTypeConst = {
                        boolean: 'boolean',
                        double: 'double',
                        int: 'int',
                        json: 'json',
                        date: 'date',
                        daterange: 'daterange',
                        time: 'time',
                        timerange: 'timerange',
                        text: 'text',
                        varchar: 'varchar',
                        varchar_auto: 'varchar_auto',
                        varchar_options: 'varchar_options',
                        address: 'address',
                        enum: 'enum',
                        monetary: 'monetary',
                        phone: 'phone',
                        set: 'set',
                        activity: 'activity',
                        deal: 'deal',
                        lead: 'lead',
                        org: 'org',
                        people: 'people',
                        pipeline: 'pipeline',
                        product: 'product',
                        project: 'project',
                        stage: 'stage',
                        user: 'user',
                        billing_frequency: 'billing_frequency',
                        picture: 'picture',
                        price_list: 'price_list',
                        projects_board: 'projects_board',
                        projects_phase: 'projects_phase',
                        status: 'status',
                        visible_to: 'visible_to'
                } as const;

                export type GetFieldAllOfFieldTypeConst = typeof GetFieldAllOfFieldTypeConst[keyof typeof GetFieldAllOfFieldTypeConst];


