/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
* 
* @export
* @interface MergeOrganizationsRequest
*/
export interface MergeOrganizationsRequest {
    /**
    * The ID of the organization that the organization will be merged with
    * @type {number}
    */
    'merge_with_id': number;
}

