/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { AddDealField200Response } from '../models';
// @ts-ignore
import { AddDealFieldOptions200Response } from '../models';
// @ts-ignore
import { AddDealFieldOptionsRequestInner } from '../models';
// @ts-ignore
import { AddDealFieldRequest } from '../models';
// @ts-ignore
import { DeleteDealField200Response } from '../models';
// @ts-ignore
import { DeleteDealFieldOptionsRequestInner } from '../models';
// @ts-ignore
import { GetDealFields200Response } from '../models';
// @ts-ignore
import { UpdateDealFieldOptionsRequestInner } from '../models';
// @ts-ignore
import { UpdateDealFieldRequest } from '../models';
/**
 * DealFieldsApi - axios parameter creator
 * @export
 */
export const DealFieldsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates a new deal custom field.
         * @summary Create one deal field
         * @param {AddDealFieldRequest} AddDealFieldRequest 

         * @throws {RequiredError}
         */
        addDealField: async (AddDealFieldRequest: AddDealFieldRequest, ): Promise<RequestArgs> => {
            // verify required parameter 'AddDealFieldRequest' is not null or undefined
            assertParamExists('addDealField', 'AddDealFieldRequest', AddDealFieldRequest)
            const localVarPath = `/dealFields`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-token", configuration)

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["admin"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, };
            localVarRequestOptions.data = serializeDataIfNeeded(AddDealFieldRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Adds new options to a deal custom field that supports options (enum or set field types). This operation is atomic - all options are added or none are added. Returns only the newly added options.
         * @summary Add deal field options in bulk
         * @param {string} field_code The unique code identifying the field
         * @param {Array<AddDealFieldOptionsRequestInner>} AddDealFieldOptionsRequestInner 

         * @throws {RequiredError}
         */
        addDealFieldOptions: async (field_code: string, AddDealFieldOptionsRequestInner: Array<AddDealFieldOptionsRequestInner>, ): Promise<RequestArgs> => {
            // verify required parameter 'field_code' is not null or undefined
            assertParamExists('addDealFieldOptions', 'field_code', field_code)
            // verify required parameter 'AddDealFieldOptionsRequestInner' is not null or undefined
            assertParamExists('addDealFieldOptions', 'AddDealFieldOptionsRequestInner', AddDealFieldOptionsRequestInner)
            const localVarPath = `/dealFields/{field_code}/options`
                .replace(`{${"field_code"}}`, encodeURIComponent(String(field_code)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-token", configuration)

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["deals:full", "admin"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, };
            localVarRequestOptions.data = serializeDataIfNeeded(AddDealFieldOptionsRequestInner, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Marks a custom field as deleted.
         * @summary Delete one deal field
         * @param {string} field_code The unique code identifying the field

         * @throws {RequiredError}
         */
        deleteDealField: async (field_code: string, ): Promise<RequestArgs> => {
            // verify required parameter 'field_code' is not null or undefined
            assertParamExists('deleteDealField', 'field_code', field_code)
            const localVarPath = `/dealFields/{field_code}`
                .replace(`{${"field_code"}}`, encodeURIComponent(String(field_code)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-token", configuration)

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["admin"], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Removes existing options from a deal custom field. This operation is atomic and fails if any of the specified option IDs do not exist. Returns only the deleted options.
         * @summary Delete deal field options in bulk
         * @param {string} field_code The unique code identifying the field
         * @param {Array<DeleteDealFieldOptionsRequestInner>} DeleteDealFieldOptionsRequestInner 

         * @throws {RequiredError}
         */
        deleteDealFieldOptions: async (field_code: string, DeleteDealFieldOptionsRequestInner: Array<DeleteDealFieldOptionsRequestInner>, ): Promise<RequestArgs> => {
            // verify required parameter 'field_code' is not null or undefined
            assertParamExists('deleteDealFieldOptions', 'field_code', field_code)
            // verify required parameter 'DeleteDealFieldOptionsRequestInner' is not null or undefined
            assertParamExists('deleteDealFieldOptions', 'DeleteDealFieldOptionsRequestInner', DeleteDealFieldOptionsRequestInner)
            const localVarPath = `/dealFields/{field_code}/options`
                .replace(`{${"field_code"}}`, encodeURIComponent(String(field_code)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-token", configuration)

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["deals:full", "admin"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, };
            localVarRequestOptions.data = serializeDataIfNeeded(DeleteDealFieldOptionsRequestInner, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns metadata about a specific deal field.
         * @summary Get one deal field
         * @param {string} field_code The unique code identifying the field
         * @param {'ui_visibility' | 'important_fields' | 'required_fields' | 'ui_visibility,important_fields' | 'ui_visibility,required_fields' | 'important_fields,required_fields' | 'ui_visibility,important_fields,required_fields'} [include_fields] Optional comma separated string array of additional data namespaces to include in response

         * @throws {RequiredError}
         */
        getDealField: async (field_code: string, include_fields?: 'ui_visibility' | 'important_fields' | 'required_fields' | 'ui_visibility,important_fields' | 'ui_visibility,required_fields' | 'important_fields,required_fields' | 'ui_visibility,important_fields,required_fields', ): Promise<RequestArgs> => {
            // verify required parameter 'field_code' is not null or undefined
            assertParamExists('getDealField', 'field_code', field_code)
            const localVarPath = `/dealFields/{field_code}`
                .replace(`{${"field_code"}}`, encodeURIComponent(String(field_code)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-token", configuration)

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["deals:read", "deals:full", "admin"], configuration)

            if (include_fields !== undefined) {
                localVarQueryParameter['include_fields'] = include_fields;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns metadata about all deal fields in the company.
         * @summary Get all deal fields
         * @param {'ui_visibility' | 'important_fields' | 'required_fields' | 'ui_visibility,important_fields' | 'ui_visibility,required_fields' | 'important_fields,required_fields' | 'ui_visibility,important_fields,required_fields'} [include_fields] Optional comma separated string array of additional data namespaces to include in response
         * @param {number} [limit] For pagination, the limit of entries to be returned. If not provided, 100 items will be returned. Please note that a maximum value of 500 is allowed.
         * @param {string} [cursor] For pagination, the marker (an opaque string value) representing the first item on the next page

         * @throws {RequiredError}
         */
        getDealFields: async (include_fields?: 'ui_visibility' | 'important_fields' | 'required_fields' | 'ui_visibility,important_fields' | 'ui_visibility,required_fields' | 'important_fields,required_fields' | 'ui_visibility,important_fields,required_fields', limit?: number, cursor?: string, ): Promise<RequestArgs> => {
            const localVarPath = `/dealFields`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-token", configuration)

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["deals:read", "deals:full", "admin"], configuration)

            if (include_fields !== undefined) {
                localVarQueryParameter['include_fields'] = include_fields;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates a deal custom field. The field_code and field_type cannot be changed. At least one field must be provided in the request body.
         * @summary Update one deal field
         * @param {string} field_code The unique code identifying the field
         * @param {UpdateDealFieldRequest} UpdateDealFieldRequest 

         * @throws {RequiredError}
         */
        updateDealField: async (field_code: string, UpdateDealFieldRequest: UpdateDealFieldRequest, ): Promise<RequestArgs> => {
            // verify required parameter 'field_code' is not null or undefined
            assertParamExists('updateDealField', 'field_code', field_code)
            // verify required parameter 'UpdateDealFieldRequest' is not null or undefined
            assertParamExists('updateDealField', 'UpdateDealFieldRequest', UpdateDealFieldRequest)
            const localVarPath = `/dealFields/{field_code}`
                .replace(`{${"field_code"}}`, encodeURIComponent(String(field_code)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-token", configuration)

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["deals:full", "admin"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, };
            localVarRequestOptions.data = serializeDataIfNeeded(UpdateDealFieldRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates existing options for a deal custom field. This operation is atomic and fails if any of the specified option IDs do not exist. Returns only the updated options.
         * @summary Update deal field options in bulk
         * @param {string} field_code The unique code identifying the field
         * @param {Array<UpdateDealFieldOptionsRequestInner>} UpdateDealFieldOptionsRequestInner 

         * @throws {RequiredError}
         */
        updateDealFieldOptions: async (field_code: string, UpdateDealFieldOptionsRequestInner: Array<UpdateDealFieldOptionsRequestInner>, ): Promise<RequestArgs> => {
            // verify required parameter 'field_code' is not null or undefined
            assertParamExists('updateDealFieldOptions', 'field_code', field_code)
            // verify required parameter 'UpdateDealFieldOptionsRequestInner' is not null or undefined
            assertParamExists('updateDealFieldOptions', 'UpdateDealFieldOptionsRequestInner', UpdateDealFieldOptionsRequestInner)
            const localVarPath = `/dealFields/{field_code}/options`
                .replace(`{${"field_code"}}`, encodeURIComponent(String(field_code)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-token", configuration)

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["deals:full", "admin"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, };
            localVarRequestOptions.data = serializeDataIfNeeded(UpdateDealFieldOptionsRequestInner, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};


/**
 * DealFieldsApi - functional programming interface
 * @export
 */
export const DealFieldsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DealFieldsApiAxiosParamCreator(configuration)
    return {
        /**
         * Creates a new deal custom field.
         * @summary Create one deal field
         * @param {AddDealFieldRequest} AddDealFieldRequest 

         * @throws {RequiredError}
         */
        async addDealField(AddDealFieldRequest: AddDealFieldRequest, ): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AddDealField200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addDealField(AddDealFieldRequest, );
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Adds new options to a deal custom field that supports options (enum or set field types). This operation is atomic - all options are added or none are added. Returns only the newly added options.
         * @summary Add deal field options in bulk
         * @param {string} field_code The unique code identifying the field
         * @param {Array<AddDealFieldOptionsRequestInner>} AddDealFieldOptionsRequestInner 

         * @throws {RequiredError}
         */
        async addDealFieldOptions(field_code: string, AddDealFieldOptionsRequestInner: Array<AddDealFieldOptionsRequestInner>, ): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AddDealFieldOptions200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addDealFieldOptions(field_code, AddDealFieldOptionsRequestInner, );
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Marks a custom field as deleted.
         * @summary Delete one deal field
         * @param {string} field_code The unique code identifying the field

         * @throws {RequiredError}
         */
        async deleteDealField(field_code: string, ): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<DeleteDealField200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteDealField(field_code, );
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Removes existing options from a deal custom field. This operation is atomic and fails if any of the specified option IDs do not exist. Returns only the deleted options.
         * @summary Delete deal field options in bulk
         * @param {string} field_code The unique code identifying the field
         * @param {Array<DeleteDealFieldOptionsRequestInner>} DeleteDealFieldOptionsRequestInner 

         * @throws {RequiredError}
         */
        async deleteDealFieldOptions(field_code: string, DeleteDealFieldOptionsRequestInner: Array<DeleteDealFieldOptionsRequestInner>, ): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AddDealFieldOptions200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteDealFieldOptions(field_code, DeleteDealFieldOptionsRequestInner, );
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Returns metadata about a specific deal field.
         * @summary Get one deal field
         * @param {string} field_code The unique code identifying the field
         * @param {'ui_visibility' | 'important_fields' | 'required_fields' | 'ui_visibility,important_fields' | 'ui_visibility,required_fields' | 'important_fields,required_fields' | 'ui_visibility,important_fields,required_fields'} [include_fields] Optional comma separated string array of additional data namespaces to include in response

         * @throws {RequiredError}
         */
        async getDealField(field_code: string, include_fields?: 'ui_visibility' | 'important_fields' | 'required_fields' | 'ui_visibility,important_fields' | 'ui_visibility,required_fields' | 'important_fields,required_fields' | 'ui_visibility,important_fields,required_fields', ): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AddDealField200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDealField(field_code, include_fields, );
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Returns metadata about all deal fields in the company.
         * @summary Get all deal fields
         * @param {'ui_visibility' | 'important_fields' | 'required_fields' | 'ui_visibility,important_fields' | 'ui_visibility,required_fields' | 'important_fields,required_fields' | 'ui_visibility,important_fields,required_fields'} [include_fields] Optional comma separated string array of additional data namespaces to include in response
         * @param {number} [limit] For pagination, the limit of entries to be returned. If not provided, 100 items will be returned. Please note that a maximum value of 500 is allowed.
         * @param {string} [cursor] For pagination, the marker (an opaque string value) representing the first item on the next page

         * @throws {RequiredError}
         */
        async getDealFields(include_fields?: 'ui_visibility' | 'important_fields' | 'required_fields' | 'ui_visibility,important_fields' | 'ui_visibility,required_fields' | 'important_fields,required_fields' | 'ui_visibility,important_fields,required_fields', limit?: number, cursor?: string, ): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<GetDealFields200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDealFields(include_fields, limit, cursor, );
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Updates a deal custom field. The field_code and field_type cannot be changed. At least one field must be provided in the request body.
         * @summary Update one deal field
         * @param {string} field_code The unique code identifying the field
         * @param {UpdateDealFieldRequest} UpdateDealFieldRequest 

         * @throws {RequiredError}
         */
        async updateDealField(field_code: string, UpdateDealFieldRequest: UpdateDealFieldRequest, ): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AddDealField200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateDealField(field_code, UpdateDealFieldRequest, );
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Updates existing options for a deal custom field. This operation is atomic and fails if any of the specified option IDs do not exist. Returns only the updated options.
         * @summary Update deal field options in bulk
         * @param {string} field_code The unique code identifying the field
         * @param {Array<UpdateDealFieldOptionsRequestInner>} UpdateDealFieldOptionsRequestInner 

         * @throws {RequiredError}
         */
        async updateDealFieldOptions(field_code: string, UpdateDealFieldOptionsRequestInner: Array<UpdateDealFieldOptionsRequestInner>, ): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AddDealFieldOptions200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateDealFieldOptions(field_code, UpdateDealFieldOptionsRequestInner, );
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DealFieldsApi - factory interface
 * @export
 */
export const DealFieldsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DealFieldsApiFp(configuration)
    return {
        /**
         * Creates a new deal custom field.
         * @summary Create one deal field
         * @param {DealFieldsApiAddDealFieldRequest} requestParameters Request parameters.

         * @throws {RequiredError}
         */
        addDealField(requestParameters: DealFieldsApiAddDealFieldRequest, ): Promise<AddDealField200Response> {
            return localVarFp.addDealField(requestParameters.AddDealFieldRequest, ).then((request) => request(axios, basePath));
        },
        /**
         * Adds new options to a deal custom field that supports options (enum or set field types). This operation is atomic - all options are added or none are added. Returns only the newly added options.
         * @summary Add deal field options in bulk
         * @param {DealFieldsApiAddDealFieldOptionsRequest} requestParameters Request parameters.

         * @throws {RequiredError}
         */
        addDealFieldOptions(requestParameters: DealFieldsApiAddDealFieldOptionsRequest, ): Promise<AddDealFieldOptions200Response> {
            return localVarFp.addDealFieldOptions(requestParameters.field_code, requestParameters.AddDealFieldOptionsRequestInner, ).then((request) => request(axios, basePath));
        },
        /**
         * Marks a custom field as deleted.
         * @summary Delete one deal field
         * @param {DealFieldsApiDeleteDealFieldRequest} requestParameters Request parameters.

         * @throws {RequiredError}
         */
        deleteDealField(requestParameters: DealFieldsApiDeleteDealFieldRequest, ): Promise<DeleteDealField200Response> {
            return localVarFp.deleteDealField(requestParameters.field_code, ).then((request) => request(axios, basePath));
        },
        /**
         * Removes existing options from a deal custom field. This operation is atomic and fails if any of the specified option IDs do not exist. Returns only the deleted options.
         * @summary Delete deal field options in bulk
         * @param {DealFieldsApiDeleteDealFieldOptionsRequest} requestParameters Request parameters.

         * @throws {RequiredError}
         */
        deleteDealFieldOptions(requestParameters: DealFieldsApiDeleteDealFieldOptionsRequest, ): Promise<AddDealFieldOptions200Response> {
            return localVarFp.deleteDealFieldOptions(requestParameters.field_code, requestParameters.DeleteDealFieldOptionsRequestInner, ).then((request) => request(axios, basePath));
        },
        /**
         * Returns metadata about a specific deal field.
         * @summary Get one deal field
         * @param {DealFieldsApiGetDealFieldRequest} requestParameters Request parameters.

         * @throws {RequiredError}
         */
        getDealField(requestParameters: DealFieldsApiGetDealFieldRequest, ): Promise<AddDealField200Response> {
            return localVarFp.getDealField(requestParameters.field_code, requestParameters.include_fields, ).then((request) => request(axios, basePath));
        },
        /**
         * Returns metadata about all deal fields in the company.
         * @summary Get all deal fields
         * @param {DealFieldsApiGetDealFieldsRequest} requestParameters Request parameters.

         * @throws {RequiredError}
         */
        getDealFields(requestParameters: DealFieldsApiGetDealFieldsRequest = {}, ): Promise<GetDealFields200Response> {
            return localVarFp.getDealFields(requestParameters.include_fields, requestParameters.limit, requestParameters.cursor, ).then((request) => request(axios, basePath));
        },
        /**
         * Updates a deal custom field. The field_code and field_type cannot be changed. At least one field must be provided in the request body.
         * @summary Update one deal field
         * @param {DealFieldsApiUpdateDealFieldRequest} requestParameters Request parameters.

         * @throws {RequiredError}
         */
        updateDealField(requestParameters: DealFieldsApiUpdateDealFieldRequest, ): Promise<AddDealField200Response> {
            return localVarFp.updateDealField(requestParameters.field_code, requestParameters.UpdateDealFieldRequest, ).then((request) => request(axios, basePath));
        },
        /**
         * Updates existing options for a deal custom field. This operation is atomic and fails if any of the specified option IDs do not exist. Returns only the updated options.
         * @summary Update deal field options in bulk
         * @param {DealFieldsApiUpdateDealFieldOptionsRequest} requestParameters Request parameters.

         * @throws {RequiredError}
         */
        updateDealFieldOptions(requestParameters: DealFieldsApiUpdateDealFieldOptionsRequest, ): Promise<AddDealFieldOptions200Response> {
            return localVarFp.updateDealFieldOptions(requestParameters.field_code, requestParameters.UpdateDealFieldOptionsRequestInner, ).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for addDealField operation in DealFieldsApi.
 * @export
 * @interface DealFieldsApiAddDealFieldRequest
 */
export interface DealFieldsApiAddDealFieldRequest {
    /**
     * 
     * @type {AddDealFieldRequest}
     * @memberof DealFieldsApiAddDealField
     */
    readonly AddDealFieldRequest: AddDealFieldRequest
}

/**
 * Request parameters for addDealFieldOptions operation in DealFieldsApi.
 * @export
 * @interface DealFieldsApiAddDealFieldOptionsRequest
 */
export interface DealFieldsApiAddDealFieldOptionsRequest {
    /**
     * The unique code identifying the field
     * @type {string}
     * @memberof DealFieldsApiAddDealFieldOptions
     */
    readonly field_code: string

    /**
     * 
     * @type {Array<AddDealFieldOptionsRequestInner>}
     * @memberof DealFieldsApiAddDealFieldOptions
     */
    readonly AddDealFieldOptionsRequestInner: Array<AddDealFieldOptionsRequestInner>
}

/**
 * Request parameters for deleteDealField operation in DealFieldsApi.
 * @export
 * @interface DealFieldsApiDeleteDealFieldRequest
 */
export interface DealFieldsApiDeleteDealFieldRequest {
    /**
     * The unique code identifying the field
     * @type {string}
     * @memberof DealFieldsApiDeleteDealField
     */
    readonly field_code: string
}

/**
 * Request parameters for deleteDealFieldOptions operation in DealFieldsApi.
 * @export
 * @interface DealFieldsApiDeleteDealFieldOptionsRequest
 */
export interface DealFieldsApiDeleteDealFieldOptionsRequest {
    /**
     * The unique code identifying the field
     * @type {string}
     * @memberof DealFieldsApiDeleteDealFieldOptions
     */
    readonly field_code: string

    /**
     * 
     * @type {Array<DeleteDealFieldOptionsRequestInner>}
     * @memberof DealFieldsApiDeleteDealFieldOptions
     */
    readonly DeleteDealFieldOptionsRequestInner: Array<DeleteDealFieldOptionsRequestInner>
}

/**
 * Request parameters for getDealField operation in DealFieldsApi.
 * @export
 * @interface DealFieldsApiGetDealFieldRequest
 */
export interface DealFieldsApiGetDealFieldRequest {
    /**
     * The unique code identifying the field
     * @type {string}
     * @memberof DealFieldsApiGetDealField
     */
    readonly field_code: string

    /**
     * Optional comma separated string array of additional data namespaces to include in response
     * @type {'ui_visibility' | 'important_fields' | 'required_fields' | 'ui_visibility,important_fields' | 'ui_visibility,required_fields' | 'important_fields,required_fields' | 'ui_visibility,important_fields,required_fields'}
     * @memberof DealFieldsApiGetDealField
     */
    readonly include_fields?: 'ui_visibility' | 'important_fields' | 'required_fields' | 'ui_visibility,important_fields' | 'ui_visibility,required_fields' | 'important_fields,required_fields' | 'ui_visibility,important_fields,required_fields'
}

/**
 * Request parameters for getDealFields operation in DealFieldsApi.
 * @export
 * @interface DealFieldsApiGetDealFieldsRequest
 */
export interface DealFieldsApiGetDealFieldsRequest {
    /**
     * Optional comma separated string array of additional data namespaces to include in response
     * @type {'ui_visibility' | 'important_fields' | 'required_fields' | 'ui_visibility,important_fields' | 'ui_visibility,required_fields' | 'important_fields,required_fields' | 'ui_visibility,important_fields,required_fields'}
     * @memberof DealFieldsApiGetDealFields
     */
    readonly include_fields?: 'ui_visibility' | 'important_fields' | 'required_fields' | 'ui_visibility,important_fields' | 'ui_visibility,required_fields' | 'important_fields,required_fields' | 'ui_visibility,important_fields,required_fields'

    /**
     * For pagination, the limit of entries to be returned. If not provided, 100 items will be returned. Please note that a maximum value of 500 is allowed.
     * @type {number}
     * @memberof DealFieldsApiGetDealFields
     */
    readonly limit?: number

    /**
     * For pagination, the marker (an opaque string value) representing the first item on the next page
     * @type {string}
     * @memberof DealFieldsApiGetDealFields
     */
    readonly cursor?: string
}

/**
 * Request parameters for updateDealField operation in DealFieldsApi.
 * @export
 * @interface DealFieldsApiUpdateDealFieldRequest
 */
export interface DealFieldsApiUpdateDealFieldRequest {
    /**
     * The unique code identifying the field
     * @type {string}
     * @memberof DealFieldsApiUpdateDealField
     */
    readonly field_code: string

    /**
     * 
     * @type {UpdateDealFieldRequest}
     * @memberof DealFieldsApiUpdateDealField
     */
    readonly UpdateDealFieldRequest: UpdateDealFieldRequest
}

/**
 * Request parameters for updateDealFieldOptions operation in DealFieldsApi.
 * @export
 * @interface DealFieldsApiUpdateDealFieldOptionsRequest
 */
export interface DealFieldsApiUpdateDealFieldOptionsRequest {
    /**
     * The unique code identifying the field
     * @type {string}
     * @memberof DealFieldsApiUpdateDealFieldOptions
     */
    readonly field_code: string

    /**
     * 
     * @type {Array<UpdateDealFieldOptionsRequestInner>}
     * @memberof DealFieldsApiUpdateDealFieldOptions
     */
    readonly UpdateDealFieldOptionsRequestInner: Array<UpdateDealFieldOptionsRequestInner>
}

/**
 * DealFieldsApi - object-oriented interface
 * @export
 * @class DealFieldsApi
 * @extends {BaseAPI}
 */
export class DealFieldsApi extends BaseAPI {
    /**
     * Creates a new deal custom field.
     * @summary Create one deal field
     * @param {DealFieldsApiAddDealFieldRequest} requestParameters Request parameters.

     * @throws {RequiredError}
     * @memberof DealFieldsApi
     */
    public addDealField(requestParameters: DealFieldsApiAddDealFieldRequest, ) {
        return DealFieldsApiFp(this.configuration).addDealField(requestParameters.AddDealFieldRequest, ).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Adds new options to a deal custom field that supports options (enum or set field types). This operation is atomic - all options are added or none are added. Returns only the newly added options.
     * @summary Add deal field options in bulk
     * @param {DealFieldsApiAddDealFieldOptionsRequest} requestParameters Request parameters.

     * @throws {RequiredError}
     * @memberof DealFieldsApi
     */
    public addDealFieldOptions(requestParameters: DealFieldsApiAddDealFieldOptionsRequest, ) {
        return DealFieldsApiFp(this.configuration).addDealFieldOptions(requestParameters.field_code, requestParameters.AddDealFieldOptionsRequestInner, ).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Marks a custom field as deleted.
     * @summary Delete one deal field
     * @param {DealFieldsApiDeleteDealFieldRequest} requestParameters Request parameters.

     * @throws {RequiredError}
     * @memberof DealFieldsApi
     */
    public deleteDealField(requestParameters: DealFieldsApiDeleteDealFieldRequest, ) {
        return DealFieldsApiFp(this.configuration).deleteDealField(requestParameters.field_code, ).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Removes existing options from a deal custom field. This operation is atomic and fails if any of the specified option IDs do not exist. Returns only the deleted options.
     * @summary Delete deal field options in bulk
     * @param {DealFieldsApiDeleteDealFieldOptionsRequest} requestParameters Request parameters.

     * @throws {RequiredError}
     * @memberof DealFieldsApi
     */
    public deleteDealFieldOptions(requestParameters: DealFieldsApiDeleteDealFieldOptionsRequest, ) {
        return DealFieldsApiFp(this.configuration).deleteDealFieldOptions(requestParameters.field_code, requestParameters.DeleteDealFieldOptionsRequestInner, ).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns metadata about a specific deal field.
     * @summary Get one deal field
     * @param {DealFieldsApiGetDealFieldRequest} requestParameters Request parameters.

     * @throws {RequiredError}
     * @memberof DealFieldsApi
     */
    public getDealField(requestParameters: DealFieldsApiGetDealFieldRequest, ) {
        return DealFieldsApiFp(this.configuration).getDealField(requestParameters.field_code, requestParameters.include_fields, ).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns metadata about all deal fields in the company.
     * @summary Get all deal fields
     * @param {DealFieldsApiGetDealFieldsRequest} requestParameters Request parameters.

     * @throws {RequiredError}
     * @memberof DealFieldsApi
     */
    public getDealFields(requestParameters: DealFieldsApiGetDealFieldsRequest = {}, ) {
        return DealFieldsApiFp(this.configuration).getDealFields(requestParameters.include_fields, requestParameters.limit, requestParameters.cursor, ).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updates a deal custom field. The field_code and field_type cannot be changed. At least one field must be provided in the request body.
     * @summary Update one deal field
     * @param {DealFieldsApiUpdateDealFieldRequest} requestParameters Request parameters.

     * @throws {RequiredError}
     * @memberof DealFieldsApi
     */
    public updateDealField(requestParameters: DealFieldsApiUpdateDealFieldRequest, ) {
        return DealFieldsApiFp(this.configuration).updateDealField(requestParameters.field_code, requestParameters.UpdateDealFieldRequest, ).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updates existing options for a deal custom field. This operation is atomic and fails if any of the specified option IDs do not exist. Returns only the updated options.
     * @summary Update deal field options in bulk
     * @param {DealFieldsApiUpdateDealFieldOptionsRequest} requestParameters Request parameters.

     * @throws {RequiredError}
     * @memberof DealFieldsApi
     */
    public updateDealFieldOptions(requestParameters: DealFieldsApiUpdateDealFieldOptionsRequest, ) {
        return DealFieldsApiFp(this.configuration).updateDealFieldOptions(requestParameters.field_code, requestParameters.UpdateDealFieldOptionsRequestInner, ).then((request) => request(this.axios, this.basePath));
    }
}
