/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AddPipelineResponse200AllOf } from './add-pipeline-response200-all-of';
// May contain unused imports in some cases
// @ts-ignore
import { AddPipelineResponse200AllOfData } from './add-pipeline-response200-all-of-data';
// May contain unused imports in some cases
// @ts-ignore
import { BaseResponse } from './base-response';

/**
 * @type AddPipelineResponse200
 * @export
 */
export type AddPipelineResponse200 = AddPipelineResponse200AllOf & BaseResponse;


