/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BaseOrganizationItemAllOfPictureIdAllOf } from './base-organization-item-all-of-picture-id-all-of';
// May contain unused imports in some cases
// @ts-ignore
import { PersonItemAllOfPictureIdAllOf1 } from './person-item-all-of-picture-id-all-of1';
// May contain unused imports in some cases
// @ts-ignore
import { PersonItemAllOfPictureIdAllOf1Pictures } from './person-item-all-of-picture-id-all-of1-pictures';

/**
 * @type BaseOrganizationItemAllOfPictureId
 * @export
 */
export type BaseOrganizationItemAllOfPictureId = BaseOrganizationItemAllOfPictureIdAllOf & PersonItemAllOfPictureIdAllOf1;


