/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AdditionalBaseOrganizationItemInfo } from './additional-base-organization-item-info';
// May contain unused imports in some cases
// @ts-ignore
import { BaseOrganizationItemAllOf } from './base-organization-item-all-of';
// May contain unused imports in some cases
// @ts-ignore
import { BaseOrganizationItemAllOfPictureId } from './base-organization-item-all-of-picture-id';
// May contain unused imports in some cases
// @ts-ignore
import { Owner } from './owner';

/**
 * @type BaseOrganizationItem
 * @export
 */
export type BaseOrganizationItem = AdditionalBaseOrganizationItemInfo & BaseOrganizationItemAllOf;


