/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BasicDeal
 */
export interface BasicDeal {
    /**
     * The expected close date of the deal. In ISO 8601 format: YYYY-MM-DD.
     * @type {string}
     * @memberof BasicDeal
     */
    'expected_close_date'?: string;
    /**
     * The success probability percentage of the deal. Used/shown only when `deal_probability` for the pipeline of the deal is enabled.
     * @type {number}
     * @memberof BasicDeal
     */
    'probability'?: number;
    /**
     * The optional message about why the deal was lost (to be used when status = lost)
     * @type {string}
     * @memberof BasicDeal
     */
    'lost_reason'?: string;
    /**
     * 
     * @type {string}
     * @memberof BasicDeal
     */
    'visible_to'?: BasicDealVisibleToConst;
}

export const BasicDealVisibleToConst = {
    _1: '1',
    _3: '3',
    _5: '5',
    _7: '7'
} as const;

export type BasicDealVisibleToConst = typeof BasicDealVisibleToConst[keyof typeof BasicDealVisibleToConst];


