/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DeleteActivityTypesResponse200AllOfData } from './delete-activity-types-response200-all-of-data';

/**
 * 
 * @export
 * @interface DeleteActivityTypesResponse200AllOf
 */
export interface DeleteActivityTypesResponse200AllOf {
    /**
     * 
     * @type {DeleteActivityTypesResponse200AllOfData}
     * @memberof DeleteActivityTypesResponse200AllOf
     */
    'data'?: DeleteActivityTypesResponse200AllOfData;
}

