/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FollowerData
 */
export interface FollowerData {
    /**
     * The name of the follower
     * @type {string}
     * @memberof FollowerData
     */
    'name'?: string;
    /**
     * The email of the follower
     * @type {string}
     * @memberof FollowerData
     */
    'email'?: string;
    /**
     * The user ID of the follower
     * @type {number}
     * @memberof FollowerData
     */
    'user_id'?: number;
    /**
     * The follower picture hash
     * @type {string}
     * @memberof FollowerData
     */
    'pic_hash'?: string;
}

