/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetPipelineMovementStatisticsResponse200AllOfDataAverageAgeInDays } from './get-pipeline-movement-statistics-response200-all-of-data-average-age-in-days';
// May contain unused imports in some cases
// @ts-ignore
import { GetPipelineMovementStatisticsResponse200AllOfDataMovementsBetweenStages } from './get-pipeline-movement-statistics-response200-all-of-data-movements-between-stages';
// May contain unused imports in some cases
// @ts-ignore
import { GetPipelineMovementStatisticsResponse200AllOfDataNewDeals } from './get-pipeline-movement-statistics-response200-all-of-data-new-deals';

/**
 * The pipeline object
 * @export
 * @interface GetPipelineMovementStatisticsResponse200AllOfData
 */
export interface GetPipelineMovementStatisticsResponse200AllOfData {
    /**
     * 
     * @type {GetPipelineMovementStatisticsResponse200AllOfDataMovementsBetweenStages}
     * @memberof GetPipelineMovementStatisticsResponse200AllOfData
     */
    'movements_between_stages'?: GetPipelineMovementStatisticsResponse200AllOfDataMovementsBetweenStages;
    /**
     * 
     * @type {GetPipelineMovementStatisticsResponse200AllOfDataNewDeals}
     * @memberof GetPipelineMovementStatisticsResponse200AllOfData
     */
    'new_deals'?: GetPipelineMovementStatisticsResponse200AllOfDataNewDeals;
    /**
     * 
     * @type {GetPipelineMovementStatisticsResponse200AllOfDataNewDeals}
     * @memberof GetPipelineMovementStatisticsResponse200AllOfData
     */
    'deals_left_open'?: GetPipelineMovementStatisticsResponse200AllOfDataNewDeals;
    /**
     * 
     * @type {GetPipelineMovementStatisticsResponse200AllOfDataNewDeals}
     * @memberof GetPipelineMovementStatisticsResponse200AllOfData
     */
    'won_deals'?: GetPipelineMovementStatisticsResponse200AllOfDataNewDeals;
    /**
     * 
     * @type {GetPipelineMovementStatisticsResponse200AllOfDataNewDeals}
     * @memberof GetPipelineMovementStatisticsResponse200AllOfData
     */
    'lost_deals'?: GetPipelineMovementStatisticsResponse200AllOfDataNewDeals;
    /**
     * 
     * @type {GetPipelineMovementStatisticsResponse200AllOfDataAverageAgeInDays}
     * @memberof GetPipelineMovementStatisticsResponse200AllOfData
     */
    'average_age_in_days'?: GetPipelineMovementStatisticsResponse200AllOfDataAverageAgeInDays;
}

