/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetUserPermissionsResponseAllOfData
 */
export interface GetUserPermissionsResponseAllOfData {
    /**
     * If the user can add custom fields
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_add_custom_fields'?: boolean;
    /**
     * If the user can add products
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_add_products'?: boolean;
    /**
     * If the user can add prospects as leads
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_add_prospects_as_leads'?: boolean;
    /**
     * If the user can bulk edit items
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_bulk_edit_items'?: boolean;
    /**
     * If the user can change visibility of items
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_change_visibility_of_items'?: boolean;
    /**
     * If the user can convert deals to leads
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_convert_deals_to_leads'?: boolean;
    /**
     * If the user can create workflows
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_create_own_workflow'?: boolean;
    /**
     * If the user can delete activities
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_delete_activities'?: boolean;
    /**
     * If the user can delete custom fields
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_delete_custom_fields'?: boolean;
    /**
     * If the user can delete deals
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_delete_deals'?: boolean;
    /**
     * If the user can edit custom fields
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_edit_custom_fields'?: boolean;
    /**
     * If the user can edit deals\' closed date
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_edit_deals_closed_date'?: boolean;
    /**
     * If the user can edit products
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_edit_products'?: boolean;
    /**
     * If the user can edit shared filters
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_edit_shared_filters'?: boolean;
    /**
     * If the user can export data from item lists
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_export_data_from_lists'?: boolean;
    /**
     * If the user can follow other users
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_follow_other_users'?: boolean;
    /**
     * If the user can merge deals
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_merge_deals'?: boolean;
    /**
     * If the user can merge organizations
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_merge_organizations'?: boolean;
    /**
     * If the user can merge people
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_merge_people'?: boolean;
    /**
     * If the user can modify labels
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_modify_labels'?: boolean;
    /**
     * If the user can see company-wide statistics
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_see_company_wide_statistics'?: boolean;
    /**
     * If the user can see the summary on the deals page
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_see_deals_list_summary'?: boolean;
    /**
     * If the user can see the names of hidden items
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_see_hidden_items_names'?: boolean;
    /**
     * If the user can see other users
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_see_other_users'?: boolean;
    /**
     * If the user can see other users\' statistics
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_see_other_users_statistics'?: boolean;
    /**
     * If the user can see security dashboard
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_see_security_dashboard'?: boolean;
    /**
     * If the user can share filters
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_share_filters'?: boolean;
    /**
     * If the user can share insights
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_share_insights'?: boolean;
    /**
     * If the user can use API
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_use_api'?: boolean;
    /**
     * If the user can use email tracking
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_use_email_tracking'?: boolean;
    /**
     * If the user can use import
     * @type {boolean}
     * @memberof GetUserPermissionsResponseAllOfData
     */
    'can_use_import'?: boolean;
}

