/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetPermissionSetsResponse200AllOfDataInner } from './get-permission-sets-response200-all-of-data-inner';

/**
 * 
 * @export
 * @interface GetPermissionSetsResponse200AllOf
 */
export interface GetPermissionSetsResponse200AllOf {
    /**
     * The array of permission set
     * @type {Array<GetPermissionSetsResponse200AllOfDataInner>}
     * @memberof GetPermissionSetsResponse200AllOf
     */
    'data'?: Array<GetPermissionSetsResponse200AllOfDataInner>;
}

