/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetAssociatedDealsResponseAllOfRelatedObjectsPipeline } from './get-associated-deals-response-all-of-related-objects-pipeline';

/**
 * 
 * @export
 * @interface GetRecentsResponseDataInnerAnyOf8
 */
export interface GetRecentsResponseDataInnerAnyOf8 {
    /**
     * 
     * @type {string}
     * @memberof GetRecentsResponseDataInnerAnyOf8
     */
    'item'?: GetRecentsResponseDataInnerAnyOf8ItemConst;
    /**
     * 
     * @type {number}
     * @memberof GetRecentsResponseDataInnerAnyOf8
     */
    'id'?: number;
    /**
     * 
     * @type {GetAssociatedDealsResponseAllOfRelatedObjectsPipeline}
     * @memberof GetRecentsResponseDataInnerAnyOf8
     */
    'data'?: GetAssociatedDealsResponseAllOfRelatedObjectsPipeline;
}

export const GetRecentsResponseDataInnerAnyOf8ItemConst = {
    pipeline: 'pipeline'
} as const;

export type GetRecentsResponseDataInnerAnyOf8ItemConst = typeof GetRecentsResponseDataInnerAnyOf8ItemConst[keyof typeof GetRecentsResponseDataInnerAnyOf8ItemConst];


