/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetAssociatedDealsResponse200AllOfRelatedObjectsPipeline
 */
export interface GetAssociatedDealsResponse200AllOfRelatedObjectsPipeline {
    /**
     * The ID of the pipeline
     * @type {number}
     * @memberof GetAssociatedDealsResponse200AllOfRelatedObjectsPipeline
     */
    'id'?: number;
    /**
     * The name of the pipeline
     * @type {string}
     * @memberof GetAssociatedDealsResponse200AllOfRelatedObjectsPipeline
     */
    'name'?: string;
    /**
     * The pipeline title displayed in the URL
     * @type {string}
     * @memberof GetAssociatedDealsResponse200AllOfRelatedObjectsPipeline
     */
    'url_title'?: string;
    /**
     * Defines the order of pipelines. First order (`order_nr=0`) is the default pipeline.
     * @type {number}
     * @memberof GetAssociatedDealsResponse200AllOfRelatedObjectsPipeline
     */
    'order_nr'?: number;
    /**
     * Whether this pipeline will be made inactive (hidden) or active
     * @type {boolean}
     * @memberof GetAssociatedDealsResponse200AllOfRelatedObjectsPipeline
     */
    'active'?: boolean;
    /**
     * Whether deal probability is disabled or enabled for this pipeline
     * @type {boolean}
     * @memberof GetAssociatedDealsResponse200AllOfRelatedObjectsPipeline
     */
    'deal_probability'?: boolean;
    /**
     * The pipeline creation time. Format: YYYY-MM-DD HH:MM:SS.
     * @type {string}
     * @memberof GetAssociatedDealsResponse200AllOfRelatedObjectsPipeline
     */
    'add_time'?: string;
    /**
     * The pipeline update time. Format: YYYY-MM-DD HH:MM:SS.
     * @type {string}
     * @memberof GetAssociatedDealsResponse200AllOfRelatedObjectsPipeline
     */
    'update_time'?: string;
}

