/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetLeadsResponse200DataInnerValue } from './get-leads-response200-data-inner-value';

/**
 * 
 * @export
 * @interface GetLeadsResponse200DataInner
 */
export interface GetLeadsResponse200DataInner {
    /**
     * The unique ID of the lead in the UUID format
     * @type {string}
     * @memberof GetLeadsResponse200DataInner
     */
    'id'?: string;
    /**
     * The title of the lead
     * @type {string}
     * @memberof GetLeadsResponse200DataInner
     */
    'title'?: string;
    /**
     * The ID of the user who owns the lead
     * @type {number}
     * @memberof GetLeadsResponse200DataInner
     */
    'owner_id'?: number;
    /**
     * The ID of the user who created the lead
     * @type {number}
     * @memberof GetLeadsResponse200DataInner
     */
    'creator_id'?: number;
    /**
     * The IDs of the lead labels which are associated with the lead
     * @type {Array<string>}
     * @memberof GetLeadsResponse200DataInner
     */
    'label_ids'?: Array<string>;
    /**
     * The ID of a person which this lead is linked to
     * @type {number}
     * @memberof GetLeadsResponse200DataInner
     */
    'person_id'?: number | null;
    /**
     * The ID of an organization which this lead is linked to
     * @type {number}
     * @memberof GetLeadsResponse200DataInner
     */
    'organization_id'?: number | null;
    /**
     * Defines where the lead comes from. Will be `API` if the lead was created through the Public API and will be `Manually created` if the lead was created manually through the UI. 
     * @type {string}
     * @memberof GetLeadsResponse200DataInner
     */
    'source_name'?: string;
    /**
     * A flag indicating whether the lead is archived or not
     * @type {boolean}
     * @memberof GetLeadsResponse200DataInner
     */
    'is_archived'?: boolean;
    /**
     * A flag indicating whether the lead was seen by someone in the Pipedrive UI
     * @type {boolean}
     * @memberof GetLeadsResponse200DataInner
     */
    'was_seen'?: boolean;
    /**
     * 
     * @type {GetLeadsResponse200DataInnerValue}
     * @memberof GetLeadsResponse200DataInner
     */
    'value'?: GetLeadsResponse200DataInnerValue;
    /**
     * The date of when the deal which will be created from the lead is expected to be closed. In ISO 8601 format: YYYY-MM-DD.
     * @type {string}
     * @memberof GetLeadsResponse200DataInner
     */
    'expected_close_date'?: string | null;
    /**
     * The ID of the next activity associated with the lead
     * @type {number}
     * @memberof GetLeadsResponse200DataInner
     */
    'next_activity_id'?: number | null;
    /**
     * The date and time of when the lead was created. In ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.
     * @type {string}
     * @memberof GetLeadsResponse200DataInner
     */
    'add_time'?: string;
    /**
     * The date and time of when the lead was last updated. In ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.
     * @type {string}
     * @memberof GetLeadsResponse200DataInner
     */
    'update_time'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetLeadsResponse200DataInner
     */
    'visible_to'?: GetLeadsResponse200DataInnerVisibleToConst;
    /**
     * The BCC email of the lead
     * @type {string}
     * @memberof GetLeadsResponse200DataInner
     */
    'cc_email'?: string;
}

export const GetLeadsResponse200DataInnerVisibleToConst = {
    _1: '1',
    _3: '3',
    _5: '5',
    _7: '7'
} as const;

export type GetLeadsResponse200DataInnerVisibleToConst = typeof GetLeadsResponse200DataInnerVisibleToConst[keyof typeof GetLeadsResponse200DataInnerVisibleToConst];


