/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The response data
 * @export
 * @interface GetRolePipelines200AllOfData
 */
export interface GetRolePipelines200AllOfData {
    /**
     * Either visible or hidden pipeline ids
     * @type {Array<number>}
     * @memberof GetRolePipelines200AllOfData
     */
    'pipeline_ids'?: Array<number>;
    /**
     * Whether visible or hidden pipeline ids were returned
     * @type {boolean}
     * @memberof GetRolePipelines200AllOfData
     */
    'visible'?: boolean;
}

