/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetAssociatedFollowersResponse2001DataInnerAllOf1
 */
export interface GetAssociatedFollowersResponse2001DataInnerAllOf1 {
    /**
     * The user ID of the follower related to the item
     * @type {number}
     * @memberof GetAssociatedFollowersResponse2001DataInnerAllOf1
     */
    'user_id'?: number;
    /**
     * The ID of the follower
     * @type {number}
     * @memberof GetAssociatedFollowersResponse2001DataInnerAllOf1
     */
    'id'?: number;
    /**
     * The date and time of adding the follower to the item
     * @type {string}
     * @memberof GetAssociatedFollowersResponse2001DataInnerAllOf1
     */
    'add_time'?: string;
}

