/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetRecentsResponseDataInnerAnyOf11Data } from './get-recents-response-data-inner-any-of11-data';

/**
 * 
 * @export
 * @interface GetRecentsResponseDataInnerAnyOf11
 */
export interface GetRecentsResponseDataInnerAnyOf11 {
    /**
     * 
     * @type {string}
     * @memberof GetRecentsResponseDataInnerAnyOf11
     */
    'item'?: GetRecentsResponseDataInnerAnyOf11ItemConst;
    /**
     * 
     * @type {number}
     * @memberof GetRecentsResponseDataInnerAnyOf11
     */
    'id'?: number;
    /**
     * 
     * @type {GetRecentsResponseDataInnerAnyOf11Data}
     * @memberof GetRecentsResponseDataInnerAnyOf11
     */
    'data'?: GetRecentsResponseDataInnerAnyOf11Data;
}

export const GetRecentsResponseDataInnerAnyOf11ItemConst = {
    user: 'user'
} as const;

export type GetRecentsResponseDataInnerAnyOf11ItemConst = typeof GetRecentsResponseDataInnerAnyOf11ItemConst[keyof typeof GetRecentsResponseDataInnerAnyOf11ItemConst];


