/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetOrganizationsResponse200AllOfRelatedObjectsPicturePICTUREID } from './get-organizations-response200-all-of-related-objects-picture-pictureid';

/**
 * The picture that is associated with the item
 * @export
 * @interface GetOrganizationsResponse200AllOfRelatedObjectsPicture
 */
export interface GetOrganizationsResponse200AllOfRelatedObjectsPicture {
    /**
     * 
     * @type {GetOrganizationsResponse200AllOfRelatedObjectsPicturePICTUREID}
     * @memberof GetOrganizationsResponse200AllOfRelatedObjectsPicture
     */
    'PICTURE_ID'?: GetOrganizationsResponse200AllOfRelatedObjectsPicturePICTUREID;
}

