/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetActivitiesResponse200RelatedObjectsOrganization } from './get-activities-response200-related-objects-organization';
// May contain unused imports in some cases
// @ts-ignore
import { GetActivitiesResponse200RelatedObjectsUser } from './get-activities-response200-related-objects-user';
// May contain unused imports in some cases
// @ts-ignore
import { GetOrganizationsResponse200AllOfRelatedObjectsPicture } from './get-organizations-response200-all-of-related-objects-picture';

/**
 * 
 * @export
 * @interface GetOrganizationsResponse200AllOfRelatedObjects
 */
export interface GetOrganizationsResponse200AllOfRelatedObjects {
    /**
     * 
     * @type {GetActivitiesResponse200RelatedObjectsOrganization}
     * @memberof GetOrganizationsResponse200AllOfRelatedObjects
     */
    'organization'?: GetActivitiesResponse200RelatedObjectsOrganization;
    /**
     * 
     * @type {GetActivitiesResponse200RelatedObjectsUser}
     * @memberof GetOrganizationsResponse200AllOfRelatedObjects
     */
    'user'?: GetActivitiesResponse200RelatedObjectsUser;
    /**
     * 
     * @type {GetOrganizationsResponse200AllOfRelatedObjectsPicture}
     * @memberof GetOrganizationsResponse200AllOfRelatedObjects
     */
    'picture'?: GetOrganizationsResponse200AllOfRelatedObjectsPicture;
}

