/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MergePersonItem } from './merge-person-item';

/**
 * 
 * @export
 * @interface GetRecentsResponseDataInnerAnyOf6
 */
export interface GetRecentsResponseDataInnerAnyOf6 {
    /**
     * 
     * @type {string}
     * @memberof GetRecentsResponseDataInnerAnyOf6
     */
    'item'?: GetRecentsResponseDataInnerAnyOf6ItemConst;
    /**
     * 
     * @type {number}
     * @memberof GetRecentsResponseDataInnerAnyOf6
     */
    'id'?: number;
    /**
     * 
     * @type {MergePersonItem}
     * @memberof GetRecentsResponseDataInnerAnyOf6
     */
    'data'?: MergePersonItem;
}

export const GetRecentsResponseDataInnerAnyOf6ItemConst = {
    person: 'person'
} as const;

export type GetRecentsResponseDataInnerAnyOf6ItemConst = typeof GetRecentsResponseDataInnerAnyOf6ItemConst[keyof typeof GetRecentsResponseDataInnerAnyOf6ItemConst];


