/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetActivitiesCollectionResponse200AdditionalData } from './get-activities-collection-response200-additional-data';
// May contain unused imports in some cases
// @ts-ignore
import { OrganizationsCollectionResponseObject } from './organizations-collection-response-object';

/**
 * 
 * @export
 * @interface GetOrganizationsCollection200Response
 */
export interface GetOrganizationsCollection200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetOrganizationsCollection200Response
     */
    'success'?: boolean;
    /**
     * 
     * @type {Array<OrganizationsCollectionResponseObject>}
     * @memberof GetOrganizationsCollection200Response
     */
    'data'?: Array<OrganizationsCollectionResponseObject>;
    /**
     * 
     * @type {GetActivitiesCollectionResponse200AdditionalData}
     * @memberof GetOrganizationsCollection200Response
     */
    'additional_data'?: GetActivitiesCollectionResponse200AdditionalData;
}

