/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The pagination details in the role list
 * @export
 * @interface GetRolesResponseAllOfAdditionalDataPagination
 */
export interface GetRolesResponseAllOfAdditionalDataPagination {
    /**
     * Pagination start
     * @type {number}
     * @memberof GetRolesResponseAllOfAdditionalDataPagination
     */
    'start'?: number;
    /**
     * Items shown per page
     * @type {number}
     * @memberof GetRolesResponseAllOfAdditionalDataPagination
     */
    'limit'?: number;
    /**
     * Whether there are more list items in the collection than displayed
     * @type {boolean}
     * @memberof GetRolesResponseAllOfAdditionalDataPagination
     */
    'more_items_in_collection'?: boolean;
}

