/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetAssociatedDealsResponse200AllOfRelatedObjectsStage } from './get-associated-deals-response200-all-of-related-objects-stage';
// May contain unused imports in some cases
// @ts-ignore
import { GetStagesResponse200DataInnerAllOf } from './get-stages-response200-data-inner-all-of';

/**
 * @type GetStagesResponse200DataInner
 * @export
 */
export type GetStagesResponse200DataInner = GetAssociatedDealsResponse200AllOfRelatedObjectsStage & GetStagesResponse200DataInnerAllOf;


