/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetNoteFieldsResponse200AllOfDataInnerOptionsInner
 */
export interface GetNoteFieldsResponse200AllOfDataInnerOptionsInner {
    /**
     * 
     * @type {number}
     * @memberof GetNoteFieldsResponse200AllOfDataInnerOptionsInner
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetNoteFieldsResponse200AllOfDataInnerOptionsInner
     */
    'label'?: string;
}

