/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The person the note is attached to
 * @export
 * @interface GetNotesResponse200DataInnerPerson
 */
export interface GetNotesResponse200DataInnerPerson {
    /**
     * The name of the person the note is attached to
     * @type {string}
     * @memberof GetNotesResponse200DataInnerPerson
     */
    'name'?: string;
}

