/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BaseResponse } from './base-response';
// May contain unused imports in some cases
// @ts-ignore
import { GetWebhookResponseAllOf } from './get-webhook-response-all-of';
// May contain unused imports in some cases
// @ts-ignore
import { GetWebhooksResponseAllOfDataInner } from './get-webhooks-response-all-of-data-inner';

/**
 * @type GetWebhookResponse
 * @export
 */
export type GetWebhookResponse = BaseResponse & GetWebhookResponseAllOf;


