/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetRoleResponseAllOfAdditionalData } from './get-role-response-all-of-additional-data';
// May contain unused imports in some cases
// @ts-ignore
import { SubRole } from './sub-role';

/**
 * 
 * @export
 * @interface GetRoleResponseAllOf
 */
export interface GetRoleResponseAllOf {
    /**
     * 
     * @type {SubRole}
     * @memberof GetRoleResponseAllOf
     */
    'data'?: SubRole;
    /**
     * 
     * @type {GetRoleResponseAllOfAdditionalData}
     * @memberof GetRoleResponseAllOf
     */
    'additional_data'?: GetRoleResponseAllOfAdditionalData;
}

