/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetproductResponse200DataAllOf
 */
export interface GetproductResponse200DataAllOf {
    /**
     * Array of objects, each containing: currency (string), price (number), cost (number, optional), overhead_cost (number, optional)
     * @type {Array<object>}
     * @memberof GetproductResponse200DataAllOf
     */
    'prices'?: Array<object>;
}

