/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FieldsResponse200AllOfAdditionalData } from './fields-response200-all-of-additional-data';
// May contain unused imports in some cases
// @ts-ignore
import { ListPersonsResponse200AllOfRelatedObjects } from './list-persons-response200-all-of-related-objects';
// May contain unused imports in some cases
// @ts-ignore
import { PersonItem } from './person-item';

/**
 * 
 * @export
 * @interface ListPersonsResponse200AllOf
 */
export interface ListPersonsResponse200AllOf {
    /**
     * The array of persons
     * @type {Array<PersonItem>}
     * @memberof ListPersonsResponse200AllOf
     */
    'data'?: Array<PersonItem>;
    /**
     * 
     * @type {FieldsResponse200AllOfAdditionalData}
     * @memberof ListPersonsResponse200AllOf
     */
    'additional_data'?: FieldsResponse200AllOfAdditionalData;
    /**
     * 
     * @type {ListPersonsResponse200AllOfRelatedObjects}
     * @memberof ListPersonsResponse200AllOf
     */
    'related_objects'?: ListPersonsResponse200AllOfRelatedObjects;
}

