/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MailMessageDataFromInner
 */
export interface MailMessageDataFromInner {
    /**
     * ID of the mail participant
     * @type {number}
     * @memberof MailMessageDataFromInner
     */
    'id'?: number;
    /**
     * Mail address of the mail participant
     * @type {string}
     * @memberof MailMessageDataFromInner
     */
    'email_address'?: string;
    /**
     * Name of the mail participant
     * @type {string}
     * @memberof MailMessageDataFromInner
     */
    'name'?: string;
    /**
     * ID of the linked person to the mail message
     * @type {number}
     * @memberof MailMessageDataFromInner
     */
    'linked_person_id'?: number;
    /**
     * Name of the linked person to the mail message
     * @type {string}
     * @memberof MailMessageDataFromInner
     */
    'linked_person_name'?: string;
    /**
     * ID of the mail message participant
     * @type {number}
     * @memberof MailMessageDataFromInner
     */
    'mail_message_party_id'?: number;
}

