/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MailMessageItemForListAllOf } from './mail-message-item-for-list-all-of';

/**
 * 
 * @export
 * @interface MailMessageResponse200AllOf1
 */
export interface MailMessageResponse200AllOf1 {
    /**
     * 
     * @type {MailMessageItemForListAllOf}
     * @memberof MailMessageResponse200AllOf1
     */
    'data'?: MailMessageItemForListAllOf;
}

