/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReceiveMessageRequestAttachmentsInner
 */
export interface ReceiveMessageRequestAttachmentsInner {
    /**
     * The ID of the attachment
     * @type {string}
     * @memberof ReceiveMessageRequestAttachmentsInner
     */
    'id': string;
    /**
     * The mime-type of the attachment
     * @type {string}
     * @memberof ReceiveMessageRequestAttachmentsInner
     */
    'type': string;
    /**
     * A URL to the file
     * @type {string}
     * @memberof ReceiveMessageRequestAttachmentsInner
     */
    'url': string;
    /**
     * The name of the attachment
     * @type {string}
     * @memberof ReceiveMessageRequestAttachmentsInner
     */
    'name'?: string;
    /**
     * The size of the attachment
     * @type {number}
     * @memberof ReceiveMessageRequestAttachmentsInner
     */
    'size'?: number;
    /**
     * A URL to a preview picture of the file
     * @type {string}
     * @memberof ReceiveMessageRequestAttachmentsInner
     */
    'preview_url'?: string;
    /**
     * If true, it will use the getMessageById endpoint for fetching updated attachment\'s urls. Find out more [here](https://pipedrive.readme.io/docs/implementing-messaging-app-extension)
     * @type {boolean}
     * @memberof ReceiveMessageRequestAttachmentsInner
     */
    'link_expires'?: boolean;
}

