/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetActivitiesResponse200AdditionalData } from './get-activities-response200-additional-data';
// May contain unused imports in some cases
// @ts-ignore
import { SearchOrganizationResponse200AllOfData } from './search-organization-response200-all-of-data';

/**
 * 
 * @export
 * @interface SearchOrganizationResponse200AllOf
 */
export interface SearchOrganizationResponse200AllOf {
    /**
     * 
     * @type {SearchOrganizationResponse200AllOfData}
     * @memberof SearchOrganizationResponse200AllOf
     */
    'data'?: SearchOrganizationResponse200AllOfData;
    /**
     * 
     * @type {GetActivitiesResponse200AdditionalData}
     * @memberof SearchOrganizationResponse200AllOf
     */
    'additional_data'?: GetActivitiesResponse200AdditionalData;
}

