/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SearchItemResponse200AllOfDataItemsInner
 */
export interface SearchItemResponse200AllOfDataItemsInner {
    /**
     * Search result relevancy
     * @type {number}
     * @memberof SearchItemResponse200AllOfDataItemsInner
     */
    'result_score'?: number;
    /**
     * Item
     * @type {object}
     * @memberof SearchItemResponse200AllOfDataItemsInner
     */
    'item'?: object;
}

