/* tslint:disable */
/* eslint-disable */
/**
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserSettingsItem
 */
export interface UserSettingsItem {
    /**
     * If the vendors are allowed to be part of the Marketplace team or not
     * @type {boolean}
     * @memberof UserSettingsItem
     */
    'marketplace_team'?: boolean;
    /**
     * The number of results shown in list by default
     * @type {number}
     * @memberof UserSettingsItem
     */
    'list_limit'?: number;
    /**
     * Whether beta app is enabled
     * @type {boolean}
     * @memberof UserSettingsItem
     */
    'beta_app'?: boolean;
    /**
     * Prevent salesphone call to override
     * @type {boolean}
     * @memberof UserSettingsItem
     */
    'prevent_salesphone_callto_override'?: boolean;
    /**
     * The destination of file upload
     * @type {string}
     * @memberof UserSettingsItem
     */
    'file_upload_destination'?: string;
    /**
     * The call to link syntax
     * @type {string}
     * @memberof UserSettingsItem
     */
    'callto_link_syntax'?: string;
    /**
     * Whether the expected close date of the deal is filled automatically or not
     * @type {boolean}
     * @memberof UserSettingsItem
     */
    'autofill_deal_expected_close_date'?: boolean;
    /**
     * Allow the vendors to duplicate a person
     * @type {string}
     * @memberof UserSettingsItem
     */
    'person_duplicate_condition'?: string;
}

